### ISSUE TITLE
Openssl genrsa numbits issue

### ISSUE THREAD

**Issue by fazakaslori** [mgcrea/node-openssl-wrapper#3]
Hy,
My issue is that there is a special function of openssl, named genrsa..it is special in the way how it manages one of its options, namely numbits. Quote from OpenSSL docuemntation:
"numbits
the size of the private key to generate in bits. This must be the last option specified. The default is 512."

Seeing how this does not work with the following syntax: openssl genrsa -numbits 2048 or openssl genrsa -2048, only accepting the syntax openssl [options] 2048, I think the library should be updated to support this particular case. An optional workaround is to use openssl genpkey, but I think the former should also be supported!

Thank you!

**Comment by mgcrea** [comment]
`openssl('genrsa', {des3: true, passout: `pass:${password}`, '2048': false})`

**Comment by lxndr** [comment]
mgcrea, this does not work.
Javascript does not ensure key-value order in objects. But 'numbits' argument for 'genrsa' must be the last. If it is not, '-out' option doesn't work and key generated into stdout instead of file.
