### ISSUE TITLE
Can you push 0.2.2 to npmjs?  

### ISSUE THREAD

**Issue by edatkinvey** [mgcrea/node-openssl-wrapper#7]
The latest version [here is 0.2.1](https://www.npmjs.com/package/openssl-wrapper)  but I am using `pkcs12` and the error handling is funky -- for now I'll pull from github, but when you get a chance can you publish 0.2.2?

Thanks!

**Comment by KyleCartmell** [comment]
Can't use the rsa command with the version published via npm. Please publish latest!

**Comment by mgcrea** [comment]
Done.
